[package]
name = "rua"
version = "0.1.0"
edition = "2021"


[dependencies]
once_cell = "1.18.0"
project-root = "0.2.2"
gc = { version = "0.5", features = ["derive"] }

[features]
default = []
debug = []
layered_debug = ["debug"]
